name: Build and deploy ASP.Net Core app to Azure Web App - JatteeksJaany

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'   # käytä projektisi .NET-versiota

      - name: Restore dependencies
        run: dotnet restore JatteeksJaany.sln   # tai csproj:n polku

      - name: Build
        run: dotnet build JatteeksJaany.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish JatteeksJaany.sln -c Release -o ${{env.DOTNET_ROOT}}/myapp --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'JatteeksJaany'   # tarkista että nimi täsmää Azure-sovelluksen nimeen
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9DA03F7C77C8421D8DDF7F4B7DC38D07 }}
